name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/workflows/common-steps
      - name: Run API tests (Hurl via Docker)
        run: |
          docker run --rm -q\
            --network host \
            -v ${{ github.workspace }}:/work \
            ghcr.io/orange-opensource/hurl:latest \
            --report-junit /work/api-test-reports/junit.xml \
            --report-html /work/api-test-reports/report.html \
            --report-json /work/api-test-reports/report.json \
            --test /work/src/test/java/api/
      - name: Upload API test reports
        uses: actions/upload-artifact@v4
        with:
          name: api-test-reports
          path: api-test-reports/
  security-scan:
    runs-on: ubuntu-latest
    needs: api-tests
    steps:
      - uses: ./common-steps
      - name: Run OWASP ZAP
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'http://localhost:8080/'
          fail_action: true
          cmd_options: '-c "api-test-reports/zap.conf"'
      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: api-test-reports/